<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_success_login</name>
   <tag></tag>
   <elementGuidId>69db59e0-7e7c-43de-8f66-f391b98823db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='angular_content']/ui-view/div/ol/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>82792868-9a44-43f0-8131-14b5327bfc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>704066e0-5343-499c-957e-d86895ab4446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Toko</value>
      <webElementGuid>76e6b414-b2d6-4aa8-a16b-b80f7423445c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;angular_content&quot;)/ui-view[1]/div[@class=&quot;page-content app-work&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;active&quot;]</value>
      <webElementGuid>df4568fa-a189-49dc-87c9-4a615c7ba3d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='angular_content']/ui-view/div/ol/li</value>
      <webElementGuid>2c75bf9b-681c-411b-8dc8-a01f6cc278ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li</value>
      <webElementGuid>c57e668d-3d64-462c-b3fc-d90db485c0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Daftar Toko' or . = 'Daftar Toko')]</value>
      <webElementGuid>612202ec-a9e2-4e9b-bf85-7bfa1ca8556f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
